name: Deploy Streamlit App to SnowflakeS

on:
  push:
    branches:
      - main  # Deploy only on pushes to the `main` branch
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      # Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install snowflake-cli
          snow --version

      # Authenticate with Snowflake
      - name: Configure Snowflake Authentication
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        run: |
          mkdir -p ~/.snowcli
          echo "[connections.snowflake]" >> ~/.snowcli/config
          echo "account = $SNOWFLAKE_ACCOUNT" >> ~/.snowcli/config
          echo "user = $SNOWFLAKE_USER" >> ~/.snowcli/config
          echo "password = $SNOWFLAKE_PASSWORD" >> ~/.snowcli/config
          echo "role = $SNOWFLAKE_ROLE" >> ~/.snowcli/config
          echo "database = $SNOWFLAKE_DATABASE" >> ~/.snowcli/config
          echo "schema = $SNOWFLAKE_SCHEMA" >> ~/.snowcli/config

      # Deploy the Streamlit app
      - name: Deploy to Snowflake
        run: |
          snow streamlit deploy sales_app

      # Post-deployment validation (Optional)
      - name: Validate Deployment
        run: |
          snow app describe --name streamlit_app_name
